export enum BadgeType {
    BUG_HUNTER = "BUG_HUNTER",
    SPEED_DEMON = "SPEED_DEMON",
    PERFECTIONIST = "PERFECTIONIST",
    TEAM_PLAYER = "TEAM_PLAYER",
    MARATHON = "MARATHON",
    QUALITY_MASTER = "QUALITY_MASTER",
    FIRST_BLOOD = "FIRST_BLOOD",
    CENTURY = "CENTURY",
}