export enum TicketStatus {
  TODO = "A_FAIRE",
  IN_PROGRESS = "EN_COURS",
  REVIEW = "REVISION",
  CHANGE_REQUEST = "DEMANDE_MODIFICATION",
  TEST = "TEST",
  TEST_KO = "TEST_KO",
  TEST_OK = "TEST_OK",
  PRODUCTION = "PRODUCTION"
}